source 'https://rubygems.org'

gem 'jekyll', '~> 1.4.0'
gem 'bootstrap-sass', '~> 3.0.3.0', github: 'thomas-mcdonald/bootstrap-sass'
gem 'sass', '~> 3.2.12'
gem 'rb-fsevent', '~> 0.9.3'
gem 'liquid', '~> 2.5.3'
gem 'maruku', '~> 0.7.0'
gem 'redcarpet', '~> 2.3.0'
gem 'dotenv', '~> 0.9.0'
gem 'jekyll-assets', '~> 0.7.4'
gem 'uglifier', '~> 2.2.1'
gem "font-awesome-sass", "~> 4.0.2"
gem 'therubyracer'
gem 'mina', '~> 0.3.0'
